// src/error-handling/types.ts

/**
 * Defines the types of errors that can occur in the application.
 * This enum provides a clear and consistent way to identify errors.
 */
export enum ErrorType {
  // HAR File Processing Errors
  EMPTY_HAR = 'EMPTY_HAR',
  INVALID_HAR_FORMAT = 'INVALID_HAR_FORMAT',
  HAR_PARSING_ERROR = 'HAR_PARSING_ERROR',
  NO_REQUESTS_FOUND = 'NO_REQUESTS_FOUND',
  NO_RELEVANT_REQUESTS = 'NO_RELEVANT_REQUESTS',

  // Flow Analysis Errors
  STATE_TRANSITION_ERROR = 'STATE_TRANSITION_ERROR',
  TEMPORAL_CORRELATION_ERROR = 'TEMPORAL_CORRELATION_ERROR',
  BEHAVIORAL_PATTERN_ERROR = 'BEHAVIORAL_PATTERN_ERROR',
  FLOW_VALIDATION_ERROR = 'FLOW_VALIDATION_ERROR',

  // Syntax Compliance Errors
  SYNTAX_VALIDATION_ERROR = 'SYNTAX_VALIDATION_ERROR',
  BLOCK_OPTIMIZATION_ERROR = 'BLOCK_OPTIMIZATION_ERROR',
  VARIABLE_LIFECYCLE_ERROR = 'VARIABLE_LIFECYCLE_ERROR',

  // Token and Dependency Errors
  TOKEN_DETECTION_ERROR = 'TOKEN_DETECTION_ERROR',
  REQUEST_DEPENDENCY_ERROR = 'REQUEST_DEPENDENCY_ERROR',
}
