// src/error-handling/types.ts

/**
 * Defines the types of errors that can occur during HAR processing and analysis.
 */
export enum ErrorType {
  // HAR File Errors
  EMPTY_HAR = 'EMPTY_HAR',
  INVALID_HAR_FORMAT = 'INVALID_HAR_FORMAT',
  HAR_PARSING_ERROR = 'HAR_PARSING_ERROR',
  NO_REQUESTS_FOUND = 'NO_REQUESTS_FOUND',
  NO_RELEVANT_REQUESTS = 'NO_RELEVANT_REQUESTS',

  // Flow Analysis Errors
  STATE_TRANSITION_ERROR = 'STATE_TRANSITION_ERROR',
  TEMPORAL_CORRELATION_ERROR = 'TEMPORAL_CORRELATION_ERROR',
  BEHAVIORAL_PATTERN_ERROR = 'BEHAVIORAL_PATTERN_ERROR',
  FLOW_VALIDATION_ERROR = 'FLOW_VALIDATION_ERROR',

  // Syntax Compliance Errors
  SYNTAX_VALIDATION_ERROR = 'SYNTAX_VALIDATION_ERROR',
  BLOCK_OPTIMIZATION_ERROR = 'BLOCK_OPTIMIZATION_ERROR',
  VARIABLE_LIFECYCLE_ERROR = 'VARIABLE_LIFECYCLE_ERROR',

  // Token and Dependency Errors
  TOKEN_DETECTION_ERROR = 'TOKEN_DETECTION_ERROR',
  REQUEST_DEPENDENCY_ERROR = 'REQUEST_DEPENDENCY_ERROR',

  // MFA and Optimization Errors
  MFA_FLOW_ERROR = 'MFA_FLOW_ERROR',
  REQUEST_OPTIMIZATION_ERROR = 'REQUEST_OPTIMIZATION_ERROR',

  // General Application Errors
  ANALYSIS_MODE_ERROR = 'ANALYSIS_MODE_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
